### ISSUE TITLE
need Resistor on pin PB9     ------> I2C1_SDA  internal not enough Resistor 

### ISSUE THREAD

**Issue by Geromino** [melexis/mlx90632-example#3]
i used stm32f4discovery  when in define i2c1   the pins was pb6/7  but i didnt work 
i change pb7 to pb9 that have  Resistor see 
https://www.st.com/content/ccc/resource/technical/document/user_manual/70/fe/4a/3f/e7/e1/4f/7d/DM00039084.pdf/files/DM00039084.pdf/jcr:content/translations/en.DM00039084.pdf

figure 10

**Comment by Letme** [comment]
Thanks for the information. Could you maybe update the README in the repo to include the wiring diagram for stm32f4discovery?

**Comment by Geromino** [comment]
how  add the  scheme  to repo   upload file forbidden

**Comment by Geromino** [comment]
i also  did change  the readme file  i send pull request

**Comment by Letme** [comment]
Closed via #5

**Comment by Geromino** [comment]
No problem
